# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-USB-MissileLauncher-RocketBaby
version:      1.01
version_from: lib/Device/USB/MissileLauncher/RocketBaby.pm
installdirs:  site
requires:
    Device::USB:                   0.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
